package ox4li::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'ox4li::Schema',
    
    connect_info => {
        dsn => 'dbi:SQLite:db.sqlite',
        user => '',
        password => '',
        on_connect_do => q{PRAGMA foreign_keys = ON},
    }
);

=head1 NAME

ox4li::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<ox4li>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<ox4li::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.59

=head1 AUTHOR

Charlie Harvey

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
